### ISSUE TITLE
What is a "Product Owner"?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-owner-guide#1]
What is a "_Product Owner_", how can I tell if I _am_ one...? :confused:

**Comment by iteles** [comment]
Good question :see_no_evil: :wink:

**Comment by nelsonic** [comment]
A product owner is a person who makes decisions.
They also make wild assumptions and expect developers to be mind-readers.
Fair description? :stuck_out_tongue_winking_eye:

**Comment by nelsonic** [comment]
@iteles can the creation of this repo (_and corresponding blog post_) be delegated to a VA?

**Comment by Cleop** [comment]
**A Product Owner (PO)** is someone who represents the views and needs of the target audience, stakeholders and the business they represent in agile scrum methodology. They must understand and communicate the vision of the product to the rest of the team.

They are the liaison between customers and the development team. This means that they are responsible for working with stakeholders and user groups to determine their needs. Then through collaboration with the Scrum Master and developer team they prioritise and discuss these ideas moulding them into features to be built.

**PO Responsibilities:**
- Owner and creator of the product backlog*.
- Adding new features to the backlog.
- Prioritizing the backlog.
- Approving or critiquing development work for release.
- Involving customers or users and getting their feedback to continuously shape the product development.
- Maintaining and updating the backlog: adjusting the features and priority as needed after each sprint or iteration.

*product backlog: a prioritised features list for the product found on github.


@iteles @nelsonic  - do you think this definition is sufficient? I know you mentioned a blog post and therefore potentially something more lengthy but given the number of issues in this repo and therefore how much is likely to end up in the readme, I was thinking of starting concise.

If you're happy with this then I'll get crafting for the readme!

**Comment by nelsonic** [comment]
@Cleop looks good. possible additional points.
+ Clearly define, understand and _empathise_ with the end-user. 👩 💡 
+ Describing the user-persona(s) in as much detail as possible to make the "pain" they feel _real_ (_especially useful when the team is remote and don't often meet with the end-users_) 📝 
+ Have a clear picture of "competitors" and the "market" for similar products/service to avoid "re-inventing" something that already exists! (_i.e. don't try to replace App/Site ABC, you are wasting your time! instead find something they aren't doing or are doing poorly and focus on that!_) 🔍 
+ Attach a _business_ or _customer_ value to each story/task in the backlog to ensure that we are building features that are genuinely wanted/needed by users. 💸 
+ Be familiar with _existing_ UX/UI through personal use of other/existing Apps/services to know what can be done/re-used. ♻️ 
+ Trust that your technical team is knowledgeable/skilful/motivated and does not need "baby sitting" ... 🙄 

Also if you make the list `<ol>` instead of `<ul>` it's easier for people to point to the number.
Can't _wait_ to read what you craft! 👍

**Comment by iteles** [comment]
This is fantastic <3 I would also not that they need to have decision-making power delegated to them _in order_ to do all of the above.
