### ISSUE TITLE
How should priority labels be used? What do they mean?

### ISSUE THREAD

**Issue by Cleop** [dwyl/product-owner-guide#16]
See: https://github.com/dwyl/process-handbook/issues/76

Here's the original proposal:
<img width="723" alt="screen shot 2017-11-08 at 17 51 16" src="https://user-images.githubusercontent.com/4185328/32564932-8d95e974-c4ad-11e7-92b1-90d13582c0ad.png">

We have 5 priority labels. Issues are worked on in priority order from 1 down to 5. `priority 1` is reserved for emergency use e.g. the live site crashing. In most situations when there are no open `priority 1` issues, `priority 2` issues are therefore the first ones to be worked on.

The actual definition of each other priority will vary for each client depending on their needs but having a defined, common framework that everyone on the project understands is important and it would be good to provide a starting point.

**Comment by Cleop** [comment]
@iteles - how do you feel about this for a short text on priority labels?

We have 5 priority labels. Issues are worked on in priority order from 1 down to 5. `priority 1` is reserved for emergency use e.g. the live site crashing. In most situations when there are no open `priority 1` issues, `priority 2` issues are therefore the first ones to be worked on. Whilst at the other end of the scale a `priority 5 ` could be used for an idea for a new feature that's not been fully outlined yet.

Is there any part that you would like more detail on?

**Comment by iteles** [comment]
I would add that `priority-5` tends to be reserved for ideas stored in the backlog without a clear decision on whether they will definitely be taken forward yet.

**Comment by nelsonic** [comment]
@iteles is there a more _descriptive_ way we could refer to ideas/stories that are considered "non-priority" than `priority-5` ?
