### ISSUE TITLE
Create sample ideal issue

### ISSUE THREAD

**Issue by Cleop** [dwyl/product-owner-guide#17]
See: https://github.com/dwyl/process-handbook/issues/1

![image](https://user-images.githubusercontent.com/16775804/35054346-3732eba8-fba4-11e7-8cce-4f239e45104b.png)

This particular example doesn't have mock-ups/screenshots as the second checkbox says the delete button should follow existing conventions set out in the style guide.

**Comment by Cleop** [comment]
@iteles - is a fabricated example ok rather than a real one?

**Comment by nelsonic** [comment]
Real is usually bettererer unless you cannot find a "good enough" one ...

**Comment by Cleop** [comment]
- [x] Add a link to the original of this issue
