### ISSUE TITLE
Create an issue template for clients to use

### ISSUE THREAD

**Issue by Cleop** [dwyl/product-owner-guide#18]
See: https://github.com/dwyl/process-handbook/issues/61, linked to #5 

## Template for making an issue

**The 3 components you should include when creating an issue are:**

1. A User story
2. Acceptance Criteria
3. A screenshot of a mock-up or a bug on the site (where possible)

Followed by... any other useful/ relevant information for completing the issue.

### User Stories

A user story is a phrase which describes the what, why and who is it for of each issue. To write one complete the following three starters:

**As...** a team member - **WHO**
**I want to...** see a user story on every issue I read  - **WHAT**
**so that...** I know the context in which the issue is set to help me understand it better - **WHY**

**Here's another example:**

**As** someone in need of a bin
**I want to** be able to filter on the online shopping site by 'lid type'
**So that** I can find a bin that closes securely to stop mice getting into my bin 🐭 ❌ 🗑 🧀 

### Acceptance Criteria

Acceptance criteria are checkboxes that a developer knows they need to complete before that issue can be considered 'done'. They are the points against which the issue will be tested.

### A screenshot or mock up of a new design
A picture which illustrates what the issue should be creating or a screenshot of an existing page showing where a bug is occurring. Remember to include mock ups of both mobile and desktop views.

<img src="https://user-images.githubusercontent.com/16775804/34988677-617ac428-fab7-11e7-9f07-3c47a84d2ab5.png" width=150px />

**Comment by Cleop** [comment]
@iteles - are you happy to close this one and to keep #5 open for adding more detailed examples of acceptance criteria?

**Comment by iteles** [comment]
Did you mean to link this issue to https://github.com/dwyl/process-handbook/issues/1 rather than https://github.com/dwyl/process-handbook/issues/61 ? (See comment on duplicates in https://github.com/dwyl/process-handbook/issues/1)

**Comment by Cleop** [comment]
I did intend for it to go to #61 as I thought #1 would more be a couple of examples of actual issues that were strong examples whereas I saw this one as more of a walk through template of how to create your own issue. But maybe I'm still interpreting them differently? What's your take (we can discuss in person if easier)?

**Comment by iteles** [comment]
https://github.com/dwyl/product-owner-guide#template-for-making-an-issue 

Will need to be added to once https://github.com/dwyl/process-handbook/issues/61 is in place.
