### ISSUE TITLE
Optimal team size: Brooks' Law

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-owner-guide#2]
https://en.wikipedia.org/wiki/Brooks%E2%80%99_law

@iteles I don't know where to _add_ this... but I feel it should be included in our "_Advise to Non-Technical Founders_" ...

> Brooks' law is an observation about software project management according to which "adding human resources to a late software project makes it later".

> According to Brooks, there is an incremental person who, when added to a project, makes it take more, not less time. This is similar to the general law of diminishing returns in economics

**Comment by Cleop** [comment]
@nelsonic - were you looking for a brief definition/ summary of this to be included in this repo's readme? What take aways or practical learnings did you want to be given from it?

**Comment by nelsonic** [comment]
@Cleop yeah, we need a section on "optimal team size" with a link to this explaining that _more often than not_ adding people to a team _slows down_ delivery.
We should _briefly_ explain _why_ effectiveness/efficiency declines with too many people.
+ Time to learn and get up-to-speed with context/codebase
+ Existing (_productive_) team members time occupied by reviewing new (_far less productive_) team members work at the expense of getting on with their own. _i.e. output is cut in half not "doubled"_!
+ Overlap and "stepping on toes" where features are not isolated enough leads to **merge conflicts** (_where one person's work can "undo" someone else's_) which can take up _way_ more time.

Best time for the _whole_ team to start is at the "_ideation_" or "_Design Sprint_" stage.
Adding people to the team when the deadline is nearing more often a _strain_ on _existing_ members than a "boost" to the team.
