### ISSUE TITLE
Create a keywords glossary so that new POs can understand agile terms

### ISSUE THREAD

**Issue by Cleop** [dwyl/product-owner-guide#22]
Create a keywords glossary so that new POs can understand agile terms

E.g. Scrum Master, Backlog, UI, user testing

**Scrum Master**: tracks team progress, liaises with product owner on requirements, lends expertise on managing end to end projects, ensures features are tested when delivered and manages deployments in conjunction with technical architect and the team.
**Product backlog:** a prioritised features / to do list for the product found on github. See <-LINK TO BACKLOG SECTION ->
**Sprint Backlog**: the backlog that is aiming for completion within a given sprint period.
**Sprint**: a 1-3 week working lifecycle of planning, building, presentation and reflection. We tend to work in 2 week (10 working day) sprints.
**UI / User Interface**: how the site looks from a design perspective.
**User testing:** interviews, focus groups and other forms of research conducted with potential/actual users of your product to give feedback and provide insight into what the user's needs are. See https://github.com/dwyl/learn-user-experience-testing to learn more about user testing. ---- #15 
**Milestone**:  a visual way to group issues in github, at dwyl we create one milestone per sprint so we have somewhere to see all of the issues which we estimate to complete by the end of the sprint. See https://github.com/dwyl/github-reference for more.

**Comment by Cleop** [comment]
@iteles - are there any more definitions you want adding for now? What do you think of the ones that I've made for the words we have so far?

Do you think we should have a definition of any of the **sprint ceremonies**? I wanted to mention a **demo** as part of another issue and then wondered if POs would know what it is. I thought I could add a link to the Process Handbook readme which does define them however these definitions are written for the internal team and therefore I don't know if we think it's good for a PO to go through? What do you think?

Answer - add a link to the process handbook Ceremonies section. Have created a new issue in that repo for writing one line definitions of the ceremonies.

**Comment by iteles** [comment]
https://github.com/dwyl/product-owner-guide#glossary-of-key-terms :+1: More to be added in due course
