### ISSUE TITLE
Let the dev team know when you will be demo'ing the application

### ISSUE THREAD

**Issue by iteles** [dwyl/product-owner-guide#6]
As a product owner
I want to make sure that there are no production updates just before I demo the application
So that there is no risk of unexpected issues cropping up during demo's.

As a dev team member
I need the PO to tell me when demos are happening
So that I can avoid production updates in that timeframe.

**Comment by Cleop** [comment]
## Timing demos and deployments

The PO and the Scrum Master liaise with one another to find a time and day suitable for sprint demos and deployments. We do however recommend the following on all occasions:
- Don't deploy on a Friday, if anything breaks it may not be discovered until after the weekend or may need working on over the weekend.
- As generally we deploy after a sprint demo, for this reason we do not start 10 day sprints on Mondays as this will inevitably end with a demo and deployment on a Friday.
- To avoid bugs disrupting sprint demos the team will demo the work they completed up until a few hours before the demo. If you continue deploying to staging up until the demo you drastically increase the likelihood of a last minute rush or a semi-complete feature causing a bug and disrupting the demo.

For these reasons it is important that the PO and Scrum Master set up demos in advance so all of these factors can be taken into consideration.
