### ISSUE TITLE
Think through structure for this repo - add contents

### ISSUE THREAD

**Issue by iteles** [dwyl/product-owner-guide#9]
We need to spend some time thinking about what information it would be useful to include in this repo and what order/structure it would make the most sense in before we go ahead and start writing this up! An implementation plan if you will.

Any thoughts on this welcome.

**Comment by Cleop** [comment]
@iteles - I think going through the process handbook repo naturally brought over a number of issues to this repo. Looking at the backlog now do you feel happy with what this repo will cover so far?

I'm happy to perhaps discuss how we structure/order the various points or we could always add a contents if that would seem useful?

What do you think @iteles?

**Comment by iteles** [comment]
Contents is definitely useful - that's a good next step (worth adding as you're creating the content) and often surfaces issues in flow.
